
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: payoutpro
      POSTGRES_USER: payoutpro
      POSTGRES_PASSWORD: payoutpro
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payoutpro"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_merchants &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_HOST: db
      DB_NAME: payoutpro
      DB_USER: payoutpro
      DB_PASSWORD: payoutpro
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build: ./backend
    command: celery -A config worker --loglevel=info --concurrency=4
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_HOST: db
      DB_NAME: payoutpro
      DB_USER: payoutpro
      DB_PASSWORD: payoutpro
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_beat:
    build: ./backend
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_HOST: db
      DB_NAME: payoutpro
      DB_USER: payoutpro
      DB_PASSWORD: payoutpro
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  flower:
    build: ./backend
    command: celery -A config flower --port=5555
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      CELERY_BROKER_URL: redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  pgdata:
